# Mimic Configuration

cooldown-in-seconds: 45       # Time between each message/etc update timer. 
                              #   (Recommended 30-90)
click-cooldown-in-seconds: 5  # Number of seconds before a player can reclick the mimic.
chatter-range: 25             # Distance from Mimic needed to be to hear it.
                              #   (Recommended 10-30)
text-style: Normal            # Available: Sentence Case, Lower Case, Upper Case, Normal
use-smart-wrap: True          # Wraps text spanning multiple lines smartly.


# TALK TYPE MIMIC Setup (Note: This is the only type that exists, thus far)
# You can add as many items to the list as you'd like.
# You can use <text> to use the mimic's stored messages.
# Note: <text> also randomly shows the mimic's clue.

talk types:
  list:               # List each mimic type, then enter specifics below.
    - parrot
    - village idiot
    - slime mimic

  NPC defaults:       # You can specify mimic type defaults for each npc type
    Slime: slime mimic
    Chicken: parrot
    Villager: village idiot

                      
  parrot:             # And now in detail for each talk mimic type in the list.
    on click:         # Texts on click -- you can add more entries.
      - "It's a parrot."
      - "You pet the parrot. *BAAAWK!*"
    cooldown: "*BAAAWK! ...the parrot is not happy."    # Text triggered when click cooldown isn't met.
    texts:            # Texts that trigger randomly when players are near.
      - "A parrot squacks, '<text>'"
      - "'<text>' ...is that a parrot?"
      - "You hear a parrot nearby, '*SQUAK*!'"
      - "You hear a parrot nearby, '<text>'"
      - "*BRR BRR BRR* ...is that a parrot?"
      - "*BAAAWK* *BAAAWK*"   

  village idiot:
    on click:
      - "Oh, it's just the Village Idiot... he's an idiot."
      - "You slug the Village idiot in the arm. *OUCH!*"
      - "The Village Idiot says to you, 'text'"
    cooldown: "The village idiot says, 'Yaaarrrharrrharr!'"
    texts:
      - "'Yarharrrharr!' ...what the heck was that?"
      - "The village idiot says, '<text>' ...does that even make sense?"
      - "'<text>' says the Village Idiot, in a drunken slur."

  slime mimic:
    click:
      - "It's a jelly-like block of slime. Yuck!"
      - "The slime is filled with all kinds of stuff. Who knows where its been?"
    cooldown: "*SQUISH* *SQUISH*"
    texts:
      - "'<text>' ...was that a slime mimic?"
      - "You hear a slime mimic nearby, '<text>'"
      - "*SQUISH* *SQUISH*"


# Individual Mimic Settings (No need to edit, this will populate by itself!)

