name: Mimic
author: aufdemrand
version: 0.6
main: net.aufdemrand.mimic.Mimic
depend:
  - Citizens
commands:
  mimic:
    description: Lists mimic commands.
    usage: /mimic help
    permission: mimic.basic
